name: my-actions
on: push
jobs:
  test-make-func:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
         cache: 'npm'
     - run: make install
     - run: make test
     - run: make lint